# Generated by Django 5.2.6 on 2026-01-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_salepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial')], default='UNPAID', max_length=10),
        ),
    ]
